def calculate_confidence(llm_score, stylometric_score):
    """
    Combines Signal 1 (LLM) and Signal 2 (Stylometric).

    LLM weight: 60%
    Stylometric weight: 40%

    Returns:
    - combined confidence score
    - attribution category
    - transparency label
    """

    combined_score = (
        (llm_score * 0.60) +
        (stylometric_score * 0.40)
    )

    combined_score = round(combined_score, 2)


    # Apply thresholds from planning.md
    if combined_score >= 0.70:
        attribution = "likely_ai"

        label = (
            "Likely AI-Generated: "
            "This content appears to have been generated by AI. "
            "The system has high confidence in this assessment."
        )


    elif combined_score >= 0.40:
        attribution = "uncertain"

        label = (
            "Attribution Uncertain: "
            "The system could not confidently determine whether "
            "this content was written by a person or generated by AI."
        )


    else:
        attribution = "likely_human"

        label = (
            "Likely Human-Written: "
            "This content appears to have been written by a person. "
            "The system has high confidence in this assessment."
        )


    return {
        "confidence": combined_score,
        "attribution": attribution,
        "label": label
    }