from groq import Groq
from dotenv import load_dotenv
import os
import json

load_dotenv()

client = Groq(api_key=os.getenv("GROQ_API_KEY"))


def analyze_with_groq(text):
    prompt = f"""
You are a text attribution classifier.

Your task is to estimate the probability that this text was generated by AI.

Return ONLY JSON:

{{
    "classification": "AI" or "Human",
    "confidence": 0.0 to 1.0,
    "reason": "short explanation"
}}

Scoring rules:

0.90 - 1.00:
Very strong AI indicators:
- generic wording
- repetitive structure
- polished but impersonal tone
- predictable transitions

0.70 - 0.89:
Some AI indicators

0.40 - 0.69:
Unclear or mixed evidence

0.10 - 0.39:
Mostly human characteristics:
- personal details
- irregular phrasing
- informal tone

0.00 - 0.09:
Very strong human indicators

Text:

{text}
"""

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ],
        temperature=0
    )

    content = response.choices[0].message.content

    try:
        return json.loads(content)
    except json.JSONDecodeError:
        return {
            "classification": "Unknown",
            "confidence": 0.0,
            "reason": "Model returned invalid JSON."
        }
    
