def generate_label(confidence):

    """
    Maps confidence score to transparency label.

    Thresholds from planning.md:

    0.70 - 1.00  -> Likely AI-Generated
    0.40 - 0.69  -> Attribution Uncertain
    0.00 - 0.39  -> Likely Human-Written
    """


    if confidence >= 0.70:

        return {
            "category": "likely_ai",
            "text": (
                "Likely AI-Generated: "
                "This content appears to have been generated by AI. "
                "The system has high confidence in this assessment."
            )
        }


    elif confidence >= 0.40:

        return {
            "category": "uncertain",
            "text": (
                "Attribution Uncertain: "
                "The system could not confidently determine whether "
                "this content was written by a person or generated by AI."
            )
        }


    else:

        return {
            "category": "likely_human",
            "text": (
                "Likely Human-Written: "
                "This content appears to have been written by a person. "
                "The system has high confidence in this assessment."
            )
        }